<h1><?php echo($this->caption);?></h1>
<p>
    Um Dir die Bilder der jeweiligen Galerie anzuschauen, klicke bitte auf das
    jeweilige Vorschaubild.
</p>
<div class="alert alert-dark" role="alert">
    <strong>Anmerkung</strong>
    <p>
    Wenn ein Bild gelöscht werden soll dann schreib bitte einen entsprechenden Hinweis an
    <?php echo($this->webmaster); ?>
    </p>
</div>
<p>
    Du hast ebenfalls Bilder? Immer her damit. Wenn Du magst, kannst Du
    Dir die jeweiligen Galerien auch als Zip-Datei herunterladen. Die Archive
    enthalten die Bilder in der besten Auflösung...
</p>
<?php if($this->permission->createAllowed()): ?>
<form class="needs-validation noshow" novalidate >
    <div class="row">
        <label for="caption" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-4">
            <input
                class="form-control form-control-sm"
                type="text"
                name="caption"
                value=""
                placeholder="Gib hier den Namen der Gallerie ein..."
                maxlength="50"
                title="Gib hier bitte die Überschrift der neuen Galerie ein."
            />
        </div>
    </div>
    <div class="row">
        <label for="description" class="col-sm-2 col-form-label">
            Beschreibung
        </label>
        <div class="col-sm-9">
            <textarea
                class="form-control form-control-sm"
                name="description"
                placeholder="Hier kommt die Beschreibung rein ..."
                title="Hier kommt der Inhalt hin. Max. 65.535 Buchstaben"
                cols="30"
                rows="10"
                maxlength="65535"
            ></textarea>
        </div>
    </div>
</form>
<button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#createDialogModal">Neuer Eintrag</button>
<div style="height: 30px;"> </div>
<?php endif; ?>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script>
<script id="entry-template" type="text/x-handlebars-template">


    <div id="{{id}}" style="display: inline-block; margin-bottom: 35px; background-color: #fff; background-clip: border-box; border: 1px solid rgba(0,0,0,.125); border-radius: .25rem; width: 600px;">
        <a href="{{link}}" title="{{description}}">
            <img class="rounded-left float-left" src="{{previewImage}}" alt="{{position}}" />
        </a>
        <div style="margin-left: 12rem; margin-top: 0.5rem;">
            <h4 style="margin-bottom: 15px;">{{title}}</h4>
            {{#if deleteAllowed}}
            <div>
                <button
                    type="button"
                    class="btn btn-danger btn-sm"
                    data-toggle="modal"
                    data-target="#deleteDialogModal"
                    data-item-id="{{id}}"
                >
                    löschen
                </button>
            </div>
            {{else}}
            <p style="margin-bottom: 0;">{{date}}; {{{creator}}}</p>
            <p style="margin-bottom: 0;"><a href="{{{downloadLink}}}">{{{downloadLinkTitle}}}</a></p>
            {{/if}}
        </div>
    </div>

</script>
<div class="list-unstyled reload-data" data-url="<?php echo($this->getCurrentPath()); ?>" >
</div>






<?php /*
<?php if(count($this->galleries)): ?>
<?php foreach($this->galleries as $k => $v1):?>
<div style="display: inline-block;margin-bottom: 35px; background-color: #fff; background-clip: border-box; border: 1px solid rgba(0,0,0,.125); border-radius: .25rem; width: 600px;">
    <a href="/">
        <img class="rounded-left float-left" src="<?php echo($v1['preview']); ?>" alt="<?php echo($v1['name']);?>" />
    </a>
    <div class="container" style="margin-left: 12rem; margin-top: 0.7rem;">
        <div class="row">
            <div class="col-sm-3"><h5><strong>Name</strong></h5></div>
            <div class="col-sm-3"><h5><?php echo($v1['name']);?></h5></div>
        </div>
        <div class="row">
            <div class="col-sm-3"><strong>Datum</strong></div>
            <div class="col-sm-3"><?php echo($v1['date']);?></div>
        </div>
        <div class="row">
            <div class="col-sm-3"><strong>Erstellt von</strong></div>
            <div class="col-sm-3"><?php echo($v1['creator']);?></div>
        </div>
        <div class="row">
            <div class="col-sm-3"><strong>Download</strong></div>
            <div class="col-sm-3"><a class="download" href="<?php echo($v1['dllink']);?>"><?php echo($v1['filename']); ?></a></div>
        </div>
    </div>
</div>









<?php /*
        <?php if($this->editable): ?>
        <button class="btn btn-danger btn-sm">
            löschen
        </button>
        <?php endif; ?>


    <?php endforeach;?>



<?php endif; ?>
 *
 */?>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
