<?php

/**
 *  SFW - SimpleFrameWork
 *
 *  Copyright (C) 2013  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see
 *  http://www.gnu.org/licenses/agpl.txt.
 *
 */

?>
<h1><?php echo($this->caption);?></h1>
<div class="mt-4">
    <?php echo($this->description);?>
</div>
<small>
    Erstellt von <?php echo($this->mailaddr); ?> am <?php echo($this->creationDate); ?>
</small>
<p class="mt-4">
    Zurück zur
    <a class="link" href="?p=<?php echo($this->page);?>">
        Übersichtenseite
    </a>
</p>
    <?php if($this->permission->createAllowed()): ?>
    <div class="fileuploadArea"></div>
    <input id="curgal" type="hidden" value="<?php echo($this->id); ?>" />
    <input id="curpage" type="hidden" value="<?php echo($this->page); ?>" />
    <div class="dropzone mb-4">
        <a class="btnRemove noshow" href="#">x</a>
        <div class="noshow clearFileSelect">
            <input
                class="fileselectupload"
                type="file"
                name="file"
                style="width: 24em;"
            />
        </div>
        <div class="fileSelectDescr">
            Datei hier ablegen oder klicken zum Hochladen
        </div>
        <div class="currfile" ></div>
    </div>
    <?php endif; ?>
    <div class="d-flex flex-wrap">
        <?php foreach($this->pics as $k => $v): ?>
        <div class="p-2 ">
            <a href="<?php echo($v['lnk']);?>" rel="lightbox-gallerie">
                <img class="img-thumbnail" alt="" src="<?php echo($v['src']); ?>" title="<?php echo($v['ttp']);?>" />
            </a>
            <!--
            <div>
                <a
                    id="clid<?php /*echo($entry['id']);*/?>"
                    style="font-weight: bold; font-size: 0.8em;"
                    class="fold"
                    title="Hier klicken um Kommentare zu lesen"
                    href="#"
                >
                    12 Kommentare &#9660;
                </a>
            </div>
            -->
            <?php if($this->permission->createAllowed()): ?>
            <div class="mt-2">
                <?php if($v['pre']): ?>
                <i>Vorschaubild</i>
                <?php else: ?>
                <button
                    class="btn btn-danger btn-sm btnDel"
                    value="<?php echo($v['ttp']);?>"
                    type="submit"
                >
                    löschen
                </button>
                <button
                    class="btn btn-success btn-sm btnDel"
                    value="<?php echo($v['ttp']);?>"
                    type="submit"
                >
                    Vorschau
                </button>
                <?php endif; ?>
            </div>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>
    <?php if(count($this->pics) > 16): ?>
    <p>
        Hier geht's zurück zum <a class="link" href="#">Seitenanfang</a>
    </p>
    <?php endif; ?>