<?php

/**
 *  SFW2 - SimpleFrameWork
 *
 *  Copyright (C) 2017  Stefan Paproth
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/agpl.txt>.
 *
 */

?>
<h1><?php echo($this->title); ?></h1>
<p><?php echo($this->about); ?></p>
<?php if(!$this->permission->createAllowed()): ?>
<div class="alert alert-success" role="alert">
    <strong>Anmerkung</strong>
    <p>
    Solltest Du ebenfalls einen interessanten Artikel entdeckt haben
    dann immer her damit. Auch alte Mitteilungen sind gerne willkommen.
    Am Besten Du schickst ihn per E-Mail an <?php echo($this->webmaster);?>.
    Bitte gib den Name der Zeitung und das jeweilige Datum mit an.
    </p>
</div>
<?php else:?>
<form id="<?php echo($this->getPathSimplified()); ?>" class="noshow">
    <div class="row">
        <label for="title" class="col-sm-4 col-form-label">Artikel</label>
        <div class="col-sm-7">
            <input
                type="text"
                class="form-control form-control-sm"
                maxlength="100"
                title="Gib hier bitte die Überschrift ein."
                name="title"
                value=""
                required
            />
            <div class="invalid-feedback"></div>
        </div>
    </div>
    <div class="row">
        <label for="date" class="col-sm-4 col-form-label">Erschienen am</label>
        <div class="col-sm-4">
            <input
                class="form-control form-control-sm"
                type="date"
                name="date"
                value=""
                title="Gib hier bitte das Erscheinungsdatum an..."
                maxlength="10"
                required
            />
            <div class="invalid-feedback"></div>
        </div>
    </div>
    <div class="row">
        <label for="newspaper" class="col-sm-4 col-form-label">In folgender Zeitung</label>
        <div class="col-sm-4">
            <input
                type="text"
                class="form-control form-control-sm"
                name="source"
                value=""
                list="newspapers"
                placeholder="Gib hier bitte die Zeitung an..."
                title="Gib hier bitte die Quelle (Zeitung) ein."
                maxlength="5"
                required
            >
            <div class="invalid-feedback"></div>
            <datalist id="newspapers">
                <option value="NDZ" />
                <option value="HAZ" />
                <option value="NP" />
            </datalist>
        </div>
    </div>
    <div class="row">
        <label for="newspaper" class="col-sm-4 col-form-label">Zeitungsartikel</label>
        <div class="col-sm-7">
            <div class="fileupload">

                <!-- FIXME --- 8x ---- 8x --- !-->


                <div class="custom-file">
                    <input data-onlyimage="true" type="file" class="custom-file-input" id="customFile">
                    <div class="invalid-feedback"></div>
                    <label class="custom-file-label" for="customFile">Datei auswählen</label>
                </div>

                <script>
                $(document).ready(function () {
                    bsCustomFileInput.init();
                });
                </script>
                <div class="noshow progress mt-2">
                    <div id="progressbar-file" class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
                </div>

                    <?php /*
                <div class="dropzone">
                    <a class="btnRemove noshow" href="#">x</a>
                    <div id="fileSelectDescr_">
                        <?php if(false && $this->multiple): ?>
                        Dateien hier ablegen
                        <?php else: ?>
                        Datei hier ablegen
                        <?php endif; ?>
                    </div>
                    <div id="clearFileSelect_" class="noshow">
                        <input
                            class="fileselectupload"
                            type="file"
                            name="file"
                            <?php if(false && $this->multiple): ?>
                            multiple="multiple"
                            <?php endif; ?>
                            style="width: 24em;"
                        />
                    </div>
                    <div class="currfile"></div>
                </div>
*/ ?>
                <!-- 8x ---- 8x --- !-->

            </div>
        </div>
    </div>
</form>
<button
    type="button"
    class="btn btn-success btn-sm"
    data-toggle="modal"
    data-target="#createDialogModal"
    data-url="<?php echo($this->getCurrentPath()); ?>"
    data-form-id="<?php echo($this->getPathSimplified()); ?>"
>Neuer Eintrag</button>
<?php endif; ?>
<div class="mt-5 mb-3 reload-data" data-url="<?php echo($this->getCurrentPath()); ?>" ></div>
<button
    class="btn btn-secondary btn-sm reload-data-manually noshow"
    type="button"
    data-url="<?php echo($this->getCurrentPath()); ?>"
>Zeige weitere Einträge...</button>
<div class="modificationDate">
    Stand: <time pubdate="pubdate"><?php echo($this->modificationDate); ?></time>
</div>
